exp_name: "50k_train_dummy"

# data configs
num_examples: 43826
embedding_paths: ["/content/drive/MyDrive/Spring 2023/CSE 252D Project/50K_embeddings/50k_clip_embeddings.npy",
                  "/content/drive/MyDrive/Spring 2023/CSE 252D Project/50K_embeddings/50k_convnext_embeddings.npy",
                  "/content/drive/MyDrive/Spring 2023/CSE 252D Project/50K_embeddings/50k_clip_intgtr_embeddings.npy"]    
gt_path: "/content/drive/MyDrive/Spring 2023/CSE 252D Project/50K_embeddings/50k_gt_prompt_embeddings.npy"
train_fraction: 0.8

# model configs
num_layers: 3
num_heads: 8

# learning configs
seed: 0
batch_size: 256
learning_rate: 0.0001
num_epochs: 500