exp_name: "100k_train_final"

# data configs
num_examples: 93826
embedding_paths: ["./100k_embeddings/100k_clip_embeddings.npy",
                  "./100k_embeddings/100k_convnext_embeddings.npy",
                  "./100k_embeddings/100k_clip_intgtr_embeddings.npy"]    
gt_path: "../100k_gt_prompt_embeddings.npy"
train_fraction: 0.8

# model configs
num_layers: 3
num_heads: 8

# learning configs
seed: 100
batch_size: 256
learning_rate: 0.001
num_epochs: 500
